[package]
name = "gpi_framework"
version = "0.1.0"
edition = "2021"


[dependencies]
petgraph = { version = "0.6.5", features = ["serde-1"] }
serde = { version = "1.0.207", features = ["serde_derive"] }

# gpirs = { path = "../gpirs/" }
derive_more = { version = "1.0.0", features = ["full"] }

# pyo3 = { version = "0.22", features = ["auto-initialize"] }
pyo3 = { version = "0.21.2" }
numpy = "0.21"
