# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

from enum import Enum, auto

class PortType(Enum):
    r"""
    Holds no data, just serves as an indication of a type of data
    """
    Integer = auto()
    Real = auto()
    Complex = auto()
    String = auto()
    Flag = auto()
    Array = auto()
    Struct = auto()

